"""
Django settings for furniture project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0^&)3l=esk=08)icqveew=npsr!a%d=t^ep#%760jzjv8=@2c6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cart',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'furniture.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'furniture.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR / 'static')

STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR / "static",)
# ]


MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR / "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AWS_ACCESS_KEY_ID=os.environ.get("ASIATUYJP7SUDX6L7AOL")
AWS_SECRET_ACCESS_KEY=os.environ.get("vGXlFI44Eb+B17weNHvXRQR7CYp2khLksF4tsXsg")
AWS_SESSION_TOKEN=os.environ.get("IQoJb3JpZ2luX2VjEMv//////////wEaCXVzLWVhc3QtMSJGMEQCIF9O/ByYXqwwYJ5rAWOL0+E+PKIBgbDc+Qj68qbezfY+AiA3V4p3sCv2OBavgClV51vDF5Tr3GPQ5aYRpUGJNc2HoCr/AwgUEAMaDDI1MDczODYzNzk5MiIMHEF52wQX4Kh58mJUKtwDePXSXIuzjlZRXsvvy8HZVzo2F263N+Z9D1X2ZYGpqRAfIlNwsQCoYz24mb8wZ7YGqEuS/CIf+APGTTHRgtxpCtYjUqWACY7IfqFM5MwKKBbFz8DT8Wby0+qPMuVWvcKP1faNn+yzMaifZsdgUIVh2/7cLqB7nJ+iQxt5zWEk+cZ2QZroCPPSniImfcz9e/pKQH90iUjOm7NtG7lXMvcnqFgGMpKola7hfLP/EDk4B0ytNBxU56Lz37qQQbUzHH2KDTBiUNKBWralxEe20usv6WQSTfoesY7RhecnlvcrHtRYZQjHNjpNrTnIeHPo1VszLQ8OZOA8GMhsG/r+mZcVTc9JF9QxjIIR8ZhZhO86nFijo9SeouQy2WljZwVUyEsNexrXGlE4uLAKYYU0lb2T5M7Yof1a9XljHgKgJgaPPdE2h3KMNVv5wdwq7uHUptYWBc+6CgvP9BVWhgj48r0CyDoTVcVCxwV14mby+xYK+CANRxXwen3QurufO2Y+5CPI4XqfpbB9TfKHbdOLYERBtOZw3jL+ZcydC+pES3+X+VgMvul3fOjP7ajLM6UvDRFqSzTWuDb7REIg3QI8xW+1HsP7p71ZUvljxzoCRL75gYw+rMyrtbEfBz3CKdkwo5eJsQY6pwHzkMjxQrY7APrJql3LDNy1URkXfYgNs6uFZdDeixV753Nt9TOeGdTlZ5GiTWUsRd3nIN1KQI3dI4x3a0UayaTHMipH7umCyAtyn0ewW2ydr7AMXhQvCp5Ped3AxvRKAnNeM9GV+b9PtoAuY5AhCpQbZffRpnF7BJNfUKySpjBD3c3LQU7jmxwNdO3ADD9yaADZX5cWi8+qNqOQNLS5Lm9UFddasvchWQ==")
AWS_STORAGE_BUCKET_NAME = os.environ.get('django-tejas-furniture-cpp-s3')
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'eu-west-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERIFY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
